// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $Terminal from "./islands/Terminal.tsx";
import * as $TerminalSection from "./islands/TerminalSection.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Terminal.tsx": $Terminal,
    "./islands/TerminalSection.tsx": $TerminalSection,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
